engine:
  data-source:
    type: CSV
    csv:
      file-path: market_data.csv
#      replay-speed: 1x
      replay-speed: MAX

isotope:
  kite:
    api-key: "xxx"
    access-token: "xxx"
    api-secret: "xxx"
  strategy:
    enabled: true
    risk-limit: 10000
    allocation-per-leg: 1500000.0
  backtest:
    initial-capital: 10000.0

logging:
  level:
    root: INFO
#    com.isotope: DEBUG
